### ISSUE TITLE
missing dependancy stampy

### ISSUE THREAD

**Issue by id0Sch** [dxinteractive/react-google-auth#1]
Hi,
the lib looks great and I really want to use it.
package.json is missing `stampy`
and i would also recommend setting`react` as a peerDependancy since you use it internally.
if you don't have the time to do so, I would be happy to submit a PR.
thanks!

**Comment by poizoncc** [comment]
+1
./node_modules/react-google-auth/lib/ScriptLoaderHock.js
Module not found: Can't resolve 'stampy' in '/Users/redkeds/Work/booking/node_modules/react-google-auth/lib'

**Comment by dxinteractive** [comment]
Hey @id0Sch and @poizoncc , so sorry about this! Had no idea that anyone else was using this library and missed the notifications. I've fixed these issues in `0.4.1`. Let me know if you have any issues and I'll keep a better eye on this library.

**Comment by id0Sch** [comment]
thanks! much appreciated 👍
